export interface ConfigItem {
    id: number;
    key: string;
    value: any;
    type: "string" | "boolean" | "number" | "json";
}

// NOTE: This should match EXACTLY to the ConfigKey class in the ThreatHub Ingestor program
export enum ConfigKey {
    ENABLE_PASSWORD_AUTH = "ENABLE_PASSWORD_AUTH",
    ENABLE_MICROSOFT_AUTH = "ENABLE_MICROSOFT_AUTH",
    ENABLE_TICKETING = "ENABLE_TICKETING",

    TICKET_SYSTEM_TYPE = "TICKET_SYSTEM_TYPE",
    TICKET_SYSTEM_URL = "TICKET_SYSTEM_URL",
    TICKET_SYSTEM_CLIENT_ID = "TICKET_SYSTEM_CLIENT_ID",
    TICKET_SYSTEM_CLIENT_SECRET = "TICKET_SYSTEM_CLIENT_SECRET",
    MIN_CVE_SEVERITY_FOR_ESCALATION = "MIN_CVE_SEVERITY_FOR_ESCALATION",
    // WAIT_TIME_BEFORE_ESCALATION = "WAIT_TIME_BEFORE_ESCALATION",
    ESCALATE_PUBLIC_EXPLOIT_IMMEDIATELY = "ESCALATE_PUBLIC_EXPLOIT_IMMEDIATELY",

    HOME_TENANT_ID = "HOME_TENANT_ID",
    SITE_URL = "SITE_URL",

    ENTRA_AUTH_CLIENT_ID = "ENTRA_AUTH_CLIENT_ID",
    ENTRA_AUTH_CLIENT_SECRET = "ENTRA_AUTH_CLIENT_SECRET",
    ENTRA_BACKEND_CLIENT_ID = "ENTRA_BACKEND_CLIENT_ID",
    ENTRA_BACKEND_CLIENT_SECRET = "ENTRA_BACKEND_CLIENT_SECRET",

    DEV_LOGGING_ENABLED = "DEV_LOGGING_ENABLED",
    DEV_LOGGING_URL = "DEV_LOGGING_URL",

    INSTANCE_ID = "INSTANCE_ID",
    EXTERNAL_LOG_FORWARDING = "EXTERNAL_LOG_FORWARDING",
    SEND_EXTERNAL_HEARTBEAT = "SEND_EXTERNAL_HEARTBEAT",

    SKIP_NON_ENTRA_JOINED_DEVICES = "SKIP_NON_ENTRA_JOINED_DEVICES"
}

export enum TicketSystemType {
    NONE = "NONE",
    HALO_PSA = "HALO_PSA"
}